server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719, 被监控的端口,加入被占用会自动从8719开始依次+1扫描,直至找到违背占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'