server:
  port: 7001

#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#    #false表示不向注册中心注册自己，因为它本身就是EurekaServer
#    register-with-eureka: false
#    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
#    fetch-registry: false
#    service-url:
#      #设置与此EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己，因为它本身就是EurekaServer
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与此EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
      #cloud-eureka-server7001注册进cloud-eureka-server7002
      #defaultZone: http://eureka7002.com:7002/eureka/  #集群指向其他eureka
      defaultZone: http://eureka7001.com:7001/eureka/   #单机就是7001自己