server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false  #在理因为cloud-consumer-feign-order80只是个消费者（客户端），我们就先不把他作为一个微服务注册紧eureka了
    #是否从EurekaServer抓取已有注册信息，默认为true,单点无所谓，集群必须设置为true才能
    #配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
  ConnectTimeout: 5000
  #指建立连接后从服务端读取到可用资源所用的时间
  ReadTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug