server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false  #在理因为cloud-consumer-feign-order80只是个消费者（客户端），我们就先不把他作为一个微服务注册紧eureka了
    #是否从EurekaServer抓取已有注册信息，默认为true,单点无所谓，集群必须设置为true才能
    #配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true